apiVersion: v1
kind: Service
metadata:
  name: fl-sev-svc-np
  labels:
    app: flsys
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  selector:
    app: flsys
    version: v1